### ISSUE TITLE
Speed Below Default Creality

### ISSUE THREAD

**Issue by zbergus** [bopchong/e3v3se-orca-profile#1]
Hello :) Just wondering why you made the decision to use a lower speed then creality uses for their defaults (ie 180 on infill)? Is it just because you found the best prints being tuned witha lower speed or is there another reason?

**Comment by zbergus** [comment]
If i read the README.md properly i would have had the answer, please disreguard

**Comment by bopchong** [comment]
Hey great question! Pretty much my there's a couple of reasons for that decision;

- I was tuning printer for quality, meant lowering the speeds seemed like a good place to start. 

- Unless printing with a high-speed filament, most normal PLA's and PETG's recommend printing speeds between 50-100mm/s.

- The table I have the printer on is very wobbly :)

That being said, since tuning, if I want a quicker print there doesn't seem to be any real issue in bumping the speed up across the board. Though most of the time, print speed can be altered to a much greater degree with other settings and orientations.
